# Generated by Django 4.1.5 on 2023-01-26 04:35

import MainApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('collegeName', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='houseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='userType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='houseInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to=MainApp.models.houseInformations.upload_photo)),
                ('uploadDate', models.DateTimeField()),
                ('area', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.accounts')),
                ('houseType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.housetype')),
                ('userType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.usertype')),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='accountType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_type', to='MainApp.usertype'),
        ),
        migrations.CreateModel(
            name='accountInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField()),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID', to='MainApp.accounts')),
            ],
        ),
    ]
