# Generated by Django 4.1.5 on 2023-02-22 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='house_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='houses_for_rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('price_per_month', models.IntegerField()),
                ('area', models.IntegerField()),
                ('description', models.TextField()),
                ('price_per_water_num', models.IntegerField()),
                ('price_per_electric_num', models.IntegerField()),
                ('junk_money', models.IntegerField()),
                ('air_conditioner', models.IntegerField()),
                ('wardrobe', models.IntegerField()),
                ('fan', models.IntegerField()),
                ('wc', models.IntegerField()),
                ('cooking_area', models.IntegerField()),
                ('parking_area', models.IntegerField()),
                ('car_parking_area', models.IntegerField()),
                ('pet_allow', models.IntegerField()),
                ('coordinates', models.CharField(max_length=255, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.districts')),
                ('house_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.house_types')),
            ],
        ),
        migrations.CreateModel(
            name='provinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='wards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=255)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.districts')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='C:\\Users\\nguye\\Downloads\\Code\\code\\NCKHSV\\MainApp\\static\\assets\\img\\house_photo')),
                ('houses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.houses_for_rent')),
            ],
        ),
        migrations.AddField(
            model_name='houses_for_rent',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.provinces'),
        ),
        migrations.AddField(
            model_name='houses_for_rent',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.wards'),
        ),
        migrations.AddField(
            model_name='districts',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.provinces'),
        ),
    ]
