# Generated by Django 4.1.5 on 2023-02-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses_for_rent',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='MainApp.districts'),
        ),
        migrations.AlterField(
            model_name='houses_for_rent',
            name='house_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='MainApp.house_types'),
        ),
        migrations.AlterField(
            model_name='houses_for_rent',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='MainApp.provinces'),
        ),
        migrations.AlterField(
            model_name='houses_for_rent',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='MainApp.wards'),
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.FileField(upload_to='MainApp/static/assets/img/house_photo'),
        ),
    ]
