# Generated by Django 4.1.5 on 2023-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_admin_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='wards',
            field=models.ManyToManyField(to='MainApp.wards'),
        ),
        migrations.AddField(
            model_name='provinces',
            name='districts',
            field=models.ManyToManyField(to='MainApp.districts'),
        ),
        migrations.AddField(
            model_name='wards',
            name='streets',
            field=models.ManyToManyField(to='MainApp.streets'),
        ),
    ]
