# Generated by Django 4.1.5 on 2023-03-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_houses_for_rent_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses_for_rent',
            name='price_per_month',
            field=models.FloatField(),
        ),
    ]
