# Generated by Django 4.1.5 on 2023-03-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_houses_for_rent_price_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses_for_rent',
            name='electric_water_heater',
            field=models.FloatField(null=True),
        ),
    ]
