# Generated by Django 4.1.5 on 2023-02-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_delete_admin_account_remove_wards_streets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houses_for_rent',
            name='street',
        ),
        migrations.DeleteModel(
            name='streets',
        ),
    ]
