# Generated by Django 4.1.5 on 2023-02-21 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_remove_houses_for_rent_street_delete_streets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districts',
            name='wards',
        ),
        migrations.RemoveField(
            model_name='provinces',
            name='districts',
        ),
        migrations.AddField(
            model_name='districts',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.provinces'),
        ),
        migrations.AddField(
            model_name='wards',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.districts'),
        ),
    ]
