# Generated by Django 4.1.5 on 2023-02-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_remove_districts_wards_remove_provinces_districts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses_for_rent',
            name='coordinates',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
