# Generated by Django 4.1.5 on 2023-02-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_houses_for_rent_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.houses_for_rent')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.image')),
            ],
        ),
        migrations.AlterField(
            model_name='houses_for_rent',
            name='images',
            field=models.ManyToManyField(through='MainApp.HouseImage', to='MainApp.image'),
        ),
    ]
