# Generated by Django 4.1.5 on 2023-03-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_houses_for_rent_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses_for_rent',
            name='electric_water_heater',
            field=models.IntegerField(null=True),
        ),
    ]
