# Generated by Django 4.1.5 on 2023-02-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_houseimage_alter_houses_for_rent_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses_for_rent',
            name='images',
            field=models.ManyToManyField(to='MainApp.image'),
        ),
        migrations.DeleteModel(
            name='HouseImage',
        ),
    ]
