# Generated by Django 4.1.5 on 2023-05-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_houses_for_rent_lat_houses_for_rent_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houses_for_rent',
            name='coordinates',
        ),
    ]
