# Generated by Django 4.1.7 on 2023-05-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_remove_houses_for_rent_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districts',
            name='province',
        ),
        migrations.RemoveField(
            model_name='houses_for_rent',
            name='province',
        ),
        migrations.DeleteModel(
            name='provinces',
        ),
    ]
