# Generated by Django 4.1.7 on 2023-05-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_remove_districts_province_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houses_for_rent',
            old_name='price_per_water_num',
            new_name='water_price',
        ),
    ]
