# Generated by Django 4.2.1 on 2023-05-28 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_rename_price_per_water_num_houses_for_rent_water_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('phone', models.IntegerField()),
                ('star_rating', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.houses_for_rent')),
            ],
        ),
    ]
