# Generated by Django 4.2.1 on 2023-06-01 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_replys'),
    ]

    operations = [
        migrations.AddField(
            model_name='replys',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
