# Generated by Django 4.2.1 on 2023-06-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_replys_date_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='replys',
            new_name='replies',
        ),
    ]
